### PR TITLE
Starts over .tex code and styling into the UNC_thesis_template.tex; Updates the example .Rmd

### PR DESCRIPTION
**Pull request by bsaul**
I began incorporating the relevant bits from START_HERE_main_template.tex into UNC_thesis_template.tex. I added variables to the .Rmd YAML header for author, committee members, abstract, etc, so that these can be modified in the .Rmd file rather than the .tex file. 

For the most part, I did not change the innards of the UNC_thesis latex package. I note that some commands could be modified to be a bit more general. For example, there are `\thesisadvisora{}`, `\thesisadvisorb{}` , `\thesismembera{}`, ..., `\thesismemberd{}` commands that are somewhat restrictive in that if, for example, you had 5 members (plus an advisor) on your committee, you would need to create a new command `\thesismembere{}`. I think it would be better to have these commands dynamically generally in a for loop based on the YAML header, eg, a header of:
```
committee:
   advisors: 
      name: someone
      name: body
   members: 
      name: Glen
      name: Sarah
```

Could be read into the .tex template with a something like: `for($committee.advisors$)$\thesisadvisor{$committee.advisor$}$endfor$` and `for($committee.members$)$\thesismember{$committee.member$}$endfor$`. But the current approach works for now.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
@phoebejiang @djluckett @cttnguyen Bradley has requested that we accept his changes. You probably also see a notifcation that "this branch has no conflicts with the base branch". However, that doesn't mean it's a GOOD set of changes. So, we need to review it.

Note: There is a formal "review" part of Github, but we're gonna skip that for now. It may make sense to do this later on, once we're all more familiar with this process.

To review: 
1. Please all 3 of you read over https://help.github.com/articles/checking-out-pull-requests-locally/#platform-mac  - be sure to choose mac vs. pc.
2. Make sure you've installed the git command line stuff (I think some of you don't have that ready? let me know).
3. Follow the instructions from 1. to download the information (files & history) from Bradley's branch to your local computer. Then, you can toy around as you usually would - using your PC to see whether you can still build a Tex document with the changes Bradley has suggested, and whether or not the document looks OK. (Again, Bradley could have made changes that satisfy "no conflicts" from the git side, but perhaps his changes are just bad in terms of the end goal of having a good Tex document)

I'm out of town - could you three get together and start looking at this? Write back in this thread.

**Comment by BarkleyBG** [comment]
Also, this is a great time to file an issue. Bradley has (in his comment) said "I note that some commands could be modified to be a bit more general". This is a great comment! Please one of you 3 take what he wrote, and open up a new issue (named appropriately and informatively) and basically copy & paste his writing into a new issue. Then, we'll have a chance to work on that issue in the future.

**Comment by phoebejiang** [comment]
Tried to do it in my terminal:

**1. git remote add origin https://github.com/TarHeelBiostatistics/DoctoralThesisTexTemplate.git**

**2. git fetch origin pull/6/head:newbranch**
arning: no common commits
remote: Counting objects: 78, done.
remote: Total 78 (delta 0), reused 0 (delta 0), pack-reused 78
Unpacking objects: 100% (78/78), done.
From https://github.com/TarHeelBiostatistics/DoctoralThesisTexTemplate
 * [new ref]         refs/pull/6/head -> newbranch

**3. git checkout newbranch**
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
	README.md
Please move or remove them before you switch branches.
Aborting

Not sure what is going on. Guess we need to fix the .DSstore thing first?

**Comment by BarkleyBG** [comment]
Do you have  untracked changes in your master branch? git won't let you checkout a branch (i.e. `newbranch`) when your current branch (i.e. `master` probably) has changes. it will require you to commit them, or discard them, before checking out a different branch. (think of it as: you can't stop in the middle of the road)

**Comment by bsaul** [comment]
For some reason, I'm not able to create a new pull request to bring in the template based on @bcjaeger files. Perhaps because I already have a PR open? Can someone merge this one?

**Comment by bsaul** [comment]
Nevermind. I figured it out. One can only submit a PR from one (local) branch at a time.

**Comment by BarkleyBG** [comment]
Great work! Thank you for your efforts. I've merged and we will deal with any lingering issues later

**Pull request merged**
