### PR TITLE
Adding template files

### PR DESCRIPTION
**Pull request by bsaul**
These commits add the template files provided by previous students plus a vanilla template.tex file that can be edited to incorporate the other files.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
I'd like to merge this but first a few questions

1. Doctoral_Thesis_Tex_Template_1/README.txt is showing "^M" at the end of the lines. What is this? Is this a conversion for the CRLF line endings differences between platforms?
1. Do we want to ignore UNC_thesis_template.Rproj  and remove it from the index? Or keep it?
1. Curious, why did you revert the first comment?

**Comment by BarkleyBG** [comment]
It looks like 1. deals with CRLF. I'll be happy to merge once you confirm for 2.

**Comment by bsaul** [comment]
Yes. Ignore .Rproj. I thought I added this to .gitignore.

**Comment by BarkleyBG** [comment]
you ignored .Rproj but not *.Rproj.

Should I add the asterisk to ignore all *.Rproj and then merge?

**Comment by bsaul** [comment]
Yes.

**Comment by BarkleyBG** [comment]
I'll change the .gitignore line to *.Rproj in the master after I merge this PR in.

**Pull request merged**
