### PR TITLE
Removed and ignored .DSstore

### PR DESCRIPTION
**Pull request by phoebejiang**
This pull request is made in response to the issue #10.

I removed the .DSstore from my local machine (commit no. is ae2e733) and added *.DSstore to the .gitignore file. Please see files changed for details.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
You don't provide a description. Could you please write a description of what changes you made, possibly referencing the issue that you're attempting to fix (use the hastag notation to refer to issues or PR's)

**Comment by phoebejiang** [comment]
This pull request is made in response to the issue #10. 

I removed the .DSstore from my local machine (commit no. is ae2e733) and added *.DSstore to the .gitignore file. Please see files changed for details.

**Comment by BarkleyBG** [comment]
Thanks for the updated comment. 

1. it seems that there's still a 3rd file that needs to be removed, could you look for that?
2. I mistakenly wrote the files as `.DSstore`, but it seems that they're `.DS_Store`. Could you make that change in the .gitignore file?

Lastly, when you're done with those two, use one of the verbs [shown here](https://help.github.com/articles/closing-issues-using-keywords/) to close the issue when the PR is merged

**Comment by phoebejiang** [comment]
1. I only saw two. One in the main folder and one in Template_2. See "files changed" for those two changes. I remember there was another one in Template_3, but I don't see it anymore. Do you see a third one?

2. I fixed it on my local machine and I recommitted it. 

I assume I need to wait until the PR is merged before I close the issue?

**Comment by BarkleyBG** [comment]
1. You're right, I only see two now.
2. You may need to match cases exactly : `.DS_Store` not `.DS_store`
3. I'll demonstrate the verb usage:

Fixes #10 

The issue will auto-close when this PR is merged.

**Comment by phoebejiang** [comment]
Yeah I realized the "s" should be uppercase too.

**Pull request merged**
